### ISSUE TITLE
CloudFlare error on correcthorse.pw

### ISSUE THREAD

**Issue by heliosyne** [quantum5/correcthorsebatterystaple#36]
I realize the website is a separate thing, but this is only point of contact I could find. The sites correcthorse.pw and quantum5.ca return this CloudFlare error and have since early this morning:

"If you're the owner of this website:

The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. Please contact your hosting provider to ensure that an up-to-date and valid SSL certificate issued by a Certificate Authority is configured for this domain name on the origin server. "

If there is another party I should contact, please let me know.

**Comment by quantum5** [comment]
Thanks for letting me know. It should be fixed now.
